apiVersion: v2
name: grafana
description: my helm chart for grafana monitoring diabetes app

type: application

version: 0.1.0
appVersion: "1.0.0"

maintainers:
- email: luongphambao1901@gmail.com
  name: luongphambbao
